### ISSUE TITLE
Error TS-996002 when build with Ivy - Angular 8.2.4

### ISSUE THREAD

**Issue by pderiy** [tinymce/tinymce-angular#121]
**What is the current behavior?**
I get an error when trying to build project with IVY

**Please provide the steps to reproduce and if possible a minimal demo of the problem via 
Just enable angular IVY (described in angular official documentation)

**What is the expected behavior?**
It should just work

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or TinyMCE-Angular?**
We use: "@tinymce/tinymce-angular": "3.3.0"
Angular : 8.2.4

Error:
`ERROR in node_modules/@tinymce/tinymce-angular/editor/editor.module.d.ts(1,22): error TS-996002: Appears in the NgModule.imports of FormsControlsModule, but could not be resolved to an NgModule cl`

**Comment by SimonFc** [comment]
Tried with @tinymce/tinymce-angular@3.3.1? The latest patch fix is done for the Ivy compiler

**Comment by pderiy** [comment]
@SimonFc I tried with agular 9 and it works with new angular. So closing this issue
